# Generated by Django 4.0.5 on 2022-07-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rating_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Product',
            new_name='product',
        ),
    ]
