# Generated by Django 4.0.5 on 2022-07-29 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_product_comment_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='product',
        ),
    ]
