# Generated by Django 4.0.5 on 2022-08-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
